version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
  json:
    class: pythonjsonlogger.jsonlogger.JsonFormatter
    format: "%(asctime)s %(name)s %(levelname)s %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: json
    filename: logs/qc_bike_path.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

loggers:
  qc_bike_path:
    level: DEBUG
    handlers: [console, file]
    propagate: no
    
  aiohttp:
    level: WARNING
    handlers: [console]
    propagate: no
    
  motor:
    level: WARNING
    handlers: [console]
    propagate: no

root:
  level: INFO
  handlers: [console]